blog/urls.py
"""Defines URL patterns for blog"""

from django.urls import path
from . import views

urlpatterns = [
	# Home page
	path('', views.index, name='index'),
	
	# New post
	path('new_post/', views.new_post, name='new_post'),
	
	# Edit post
	path('edit_post/<post_id>', views.edit_post, name='edit_post'),
	
	# New comment
	path('<post_id>/new_comment', views.new_comment, name='new_comment'),
	
	# Edit comment
	path('edit_comment/<comment_id>', views.edit_comment, name='edit_comment'),
]

blog_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	# Login page
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	
	# Logout page
	path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
	
	# Registration page
	path('register/', views.register, name='register'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
	"""A blog post the user posts"""
	title = models.CharField(max_length=255)
	content = models.TextField()
	posted_on = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	private = models.BooleanField(default=False)
	
	def __str__(self):	
		"""Return a string representation of the model."""
		return self.title

class Comment(models.Model):
	"""A model that represents comments on posts."""
	content = models.TextField()
	posted_on = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
	
	def __str__(self):
		"""Returns a string representation of the model."""
		return self.content

users/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title', 'content', 'private']
		labels = {
			'title': 'Title', 
			'content': '', 
			'private': 'Private. Only logged in users will be able to see this post',
			}
		widgets = {
			'content': forms.Textarea(attrs={'cols': 80}), 
			}
		
class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['content']
		labels = {
			'content': 'Comment',
			}
		widgets = {
			'content': forms.Textarea(attrs={'cols': 80}),
			}

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Post, Comment
from .forms import PostForm, CommentForm

# Create your views here.
def index(request):
	"""The home page for blog. All blog posts will be shown on this page in reverse chronological order."""
	if request.user.is_authenticated:
		posts = Post.objects.order_by('-posted_on')
	else:
		posts = Post.objects.filter(private=False).order_by('-posted_on')
	context = {'posts': posts}
	return render(request, 'blog/index.html', context)
	

@login_required	
def new_post(request):
	"""Add a new post."""
	if request.method != 'POST':
		# No data submitted; create blank form.
		form = PostForm()
	else:
		# POST data submitted; process data.
		form = PostForm(data=request.POST)
		if form.is_valid():
			new_post = form.save(commit=False)
			new_post.author = request.user
			new_post.save()
			return HttpResponseRedirect(reverse('blog:index'))
	
	context = {'form': form}
	return render(request, 'blog/new_post.html', context)
	
def check_owner(request, written_thing):
	"""Check the post belongs to the current user."""
	if written_thing.author != request.user:
		raise Http404	

@login_required
def edit_post(request, post_id):
	"""Edit an existing post."""
	post = Post.objects.get(id=post_id)
	check_owner(request, post)
	
	if request.method != 'POST':
		# No data submitted; return prefilled form.
		form = PostForm(instance=post)
	else:
		# POST data submitted; process data
		form = PostForm(instance=post, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('blog:index'))
	
	context = {'post': post, 'form': form}
	return render(request, 'blog/edit_post.html', context)

@login_required
def new_comment(request, post_id):
	"""Write a new comment."""
	post = Post.objects.get(id=post_id)
	
	if request.method != 'POST':
		# No data submitted, load blank form
		form = CommentForm()
	else:
		# Data submitted. validate and save
		form = CommentForm(data=request.POST)
		if form.is_valid():
			new_comment = form.save(commit=False)
			new_comment.author = request.user
			new_comment.post = post
			new_comment.save()
			return HttpResponseRedirect(reverse('blog:index'))
			
	context = {'post': post, 'form': form}
	return render(request, 'blog/new_comment.html', context)

@login_required
def edit_comment(request, comment_id):
	"""Edit a comment."""
	comment = Comment.objects.get(id=comment_id)
	post = comment.post
	check_owner(request, comment)
	
	if request.method != 'POST':
		# load prefilled form
		form = CommentForm(instance=comment)
	else:
		# data submitted, validate and save
		form = CommentForm(instance=comment, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('blog:index'))
			
	context = {'comment': comment, 'post': post, 'form': form}
	return render(request, 'blog/edit_comment.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
	"""Register a new user."""
	if request.method!= 'POST':
		# Display blank registration form.
		form = UserCreationForm()
	else:
		# Process completed form
		form = UserCreationForm(data=request.POST)
		
		if form.is_valid():
			new_user = form.save()
			# Log the user in and then redirect to home page.
			authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
			login(request, authenticated_user)
			return HttpResponseRedirect(reverse('blog:index'))

	context = {'form': form}
	return render(request, 'users/register.html', context)

blog/templates/blog/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<title>Blog!</title>

	<!-- link bootstrap -->
	{% bootstrap_css %}
	{% bootstrap_javascript %}
	
	<!-- link my css files -->
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'blog/styles.css' %}">
	
  </head>
  
  <body>
  
    <!-- Static navbar -->
    <nav class="navbar navbar-inverse navbar-static-top">
	  <div class="container">

	    <div class="navbar-header">
 		  <button type="button" class="navbar-toggle collapsed"
		      data-toggle="collapse" data-target="#navbar"
			  aria-expanded="false" aria-controls="navbar">
		  </button>
		  <a class="navbar-brand" href="{% url 'blog:index' %}">Blog!</a>
		</div>

		<div id="navbar" class="navbar-collapse collapse">

		  <ul class="nav navbar-nav navbar-right">
			{% if user.is_authenticated %}
			  <li><a>Hello, {{ user.username }}.</a></li>
			  <li><a href="{% url 'users:logout' %}">log out</a></li>
			{% else %}
			  <li><a href="{% url 'users:register' %}">register</a></li>
			  <li><a href="{% url 'users:login' %}">log in</a></li>
			{% endif %}
		  </ul>
		</div><!--/.nav-collapse -->

	  </div>
	</nav>
   
    <div class="container">
		
	  <div class="page-header">
			{% block header %}{% endblock header %}
	  </div>
	  <div>
	    {% block content %}{% endblock content %}
	  </div>	
		
  </div> <!-- /container -->
     
  </body>
</html>

blog/templates/blog/edit_comment.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Edit comment</h2>
{% endblock header %}

{% block content %}

  <!-- Show the post and comments -->
  <div class="panel panel-default">
    <div class="panel-heading">
	  <h3>
		{{ post }} 
		<small>
		  Author: {{ post.author }} - Posted on: {{ post.posted_on|date:'M d, Y' }}
		</small>
	  </h3>
	</div>
	
	<div class="panel-body">
	  {{ post.content|linebreaks }}
	</div>
	
	<!-- comments -->
	<div class="panel-footer">
	  {% if post.comments.count > 0 %}
		<h4>Comments</h4>
	    {% for comment in post.comments.all %}
		  <p><strong>{{ comment.author }}:</strong> {{ comment }}</p>
	    {% endfor %}
	  {% endif %}
	  
      <!-- comment form -->
      <form action="{% url 'blog:edit_comment' comment.id %}" method='post' class="form">
	    {% csrf_token %}
	    {% bootstrap_form form %}
	
	    {% buttons %}
	      <button name="submit" class="btn btn-primary">save</button>
	    {% endbuttons %}
      </form>	
 	</div> <!-- panel footer -->
   </div> <!-- panel -->

{% endblock content %}

blog/templates/blog/edit_post.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Edit entry</h2>
{% endblock header %}

{% block content %}
  
  <form action="{% url 'blog:edit_post' post.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">save</button>
    {% endbuttons %}
  </form>

{% endblock content %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

<!-- jumbotron -->
{% block header %}
  <div class='jumbotron'>
	<h1>Share what's on your mind!</h1>
  </div>
{% endblock header %}

{% block content %}
  <!-- introduction paragraph to the blog with links to register -->
  <h2>Blog! is a platform for people to share ideas, experiences, and anything else on their mind. <a href="{% url 'users:register' %}">Register an account</a> to view all posts, comment, and write posts yourself.</h2>
  
  <!-- add a new post link -->
  <h2>
    <a href="{% url 'blog:new_post' %}">Add a new blog post.</a>
  </h2>
  
  <h2>Posts:</h2>
  
  <!-- list of posts in order by date -->
  {% for post in posts %}
    <div class="panel panel-default">
	  <div class="panel-heading">
		<h3>
		  {{ post }} 
		  <small>
			Author: {{ post.author }} - {{ post.posted_on|date:'M d, Y' }} <a href="{% url 'blog:edit_post' post.id %}">edit post</a>
		  </small>
		</h3>
	  </div>
	  <div class="panel-body">
	    {{ post.content|linebreaks }}
	  </div>
	  <!-- comments -->
	  <div class="panel-footer">
	  {% if post.comments.count > 0 %}
		<h4>Comments</h4>
	    {% for comment in post.comments.all %}
		  <p>
			<strong>{{ comment.author }}:</strong> {{ comment }}
			<small><a href="{% url 'blog:edit_comment' comment.id %}">edit</a></small>
		  </p>
			  
	    {% endfor %}
	  {% endif %}
	  <a href="{% url 'blog:new_comment' post.id %}">Comment</a>
 	  </div>
   </div> <!-- panel -->
  {% empty %}
	There are no entries for this topic yet.
  {% endfor %}
 
{% endblock content %}

blog/templates/blog/new_comment.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new comment</h2>
{% endblock header %}

{% block content %}
  <!-- Show the post and comments -->
  <div class="panel panel-default">
    <div class="panel-heading">
	  <h3>
		{{ post }} 
		<small>
		  Author: {{ post.author }} - Posted on: {{ post.posted_on|date:'M d, Y' }}
		</small>
	  </h3>
	</div>
	
	<div class="panel-body">
	  {{ post.content|linebreaks }}
	</div>
	
	<!-- comments -->
	<div class="panel-footer">
	  {% if post.comments.count > 0 %}
		<h4>Comments</h4>
	    {% for comment in post.comments.all %}
		  <p><strong>{{ comment.author }}:</strong> {{ comment }}</p>
	    {% endfor %}
	  {% endif %}
	  
      <!-- comment form -->
      <form action="{% url 'blog:new_comment' post.id %}" method='post' class="form">
	    {% csrf_token %}
	    {% bootstrap_form form %}
	
	    {% buttons %}
	      <button name="submit" class="btn btn-primary">save comment</button>
	    {% endbuttons %}
      </form>	
 	</div> <!-- panel footer -->
   </div> <!-- panel -->
  


{% endblock content %}

blog/templates/blog/new_post.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new post</h2>
{% endblock header %}

{% block content %}
  
  <form action="{% url 'blog:new_post' %}" method='post' class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	
	{% buttons %}
	  <button name="submit" class="btn btn-primary">save post</button>
	{% endbuttons %}
  </form>

{% endblock content %}

users/templates/users/login.html
{% extends "blog/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in</h2>
{% endblock header %}

{% block content %}
  
  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">Login</button>
    {% endbuttons %}
    
    <input type="hidden" name="next" value="{% url 'blog:index' %}" />
  </form>
  
{% endblock content %}

users/templates/users/register.html
{% extends "blog/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Register an account</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">register</button>
    {% endbuttons %}
    
    <input type="hidden" name="next" value="{% url 'blog:index' %}" />
  </form>
  
{% endblock content %}